name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    env:
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      # Not using npm? Change `npm ci` to `yarn install` or `pnpm i`
      - name: Install dependencies
        # run: yarn install
        run: npm ci

      # Not using npm? Change `npm run build` to `yarn build` or `pnpm run build`
      - name: Build Nuxt
        # run: yarn build:deno
        run: npm run build:deno

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "the-in-season-cup"
          entrypoint: "server/index.ts" # TODO: update entrypoint
          root: ".output"
